// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pingpong.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cfbf639ab46154b, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type PingResponse struct {
	Pong                 string   `protobuf:"bytes,2,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cfbf639ab46154b, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "v1.PingResponse")
}

func init() { proto.RegisterFile("pingpong.proto", fileDescriptor_1cfbf639ab46154b) }

var fileDescriptor_1cfbf639ab46154b = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe5, 0xb4, 0x7f, 0x7f, 0x7a, 0x41, 0x34, 0xf5, 0x54, 0x22, 0x86, 0x90, 0x09, 0x55,
	0x34, 0x6e, 0x0a, 0x53, 0x59, 0x80, 0x05, 0x89, 0xa9, 0x2a, 0x1b, 0x9b, 0x49, 0x2d, 0x63, 0x94,
	0xde, 0x6b, 0xea, 0x10, 0xc4, 0xca, 0x23, 0x80, 0x58, 0x90, 0x78, 0x2a, 0x5e, 0x81, 0x07, 0x41,
	0x71, 0xa1, 0x20, 0x75, 0xba, 0x47, 0x47, 0x9f, 0xce, 0xd1, 0x3d, 0xb0, 0x6d, 0x0d, 0x6a, 0x4b,
	0xa8, 0x53, 0xbb, 0xa0, 0x92, 0x78, 0x50, 0x65, 0xd1, 0xae, 0x26, 0xd2, 0x85, 0x12, 0xd2, 0x1a,
	0x21, 0x11, 0xa9, 0x94, 0xa5, 0x21, 0x74, 0x4b, 0x22, 0x3a, 0xf0, 0x27, 0x1f, 0x68, 0x85, 0x03,
	0xf7, 0x20, 0xb5, 0x56, 0x0b, 0x41, 0xd6, 0x13, 0xeb, 0x74, 0xb2, 0x07, 0x9b, 0x13, 0x83, 0x7a,
	0xaa, 0xee, 0xee, 0x95, 0x2b, 0x39, 0x87, 0x66, 0x5d, 0xd8, 0x63, 0x31, 0xdb, 0x6f, 0x4f, 0xbd,
	0x4e, 0x12, 0xd8, 0x5a, 0x22, 0xce, 0x12, 0x3a, 0xe5, 0x19, 0x42, 0xdd, 0x0b, 0xbe, 0x19, 0x42,
	0x3d, 0x3a, 0x87, 0x8d, 0x9a, 0x99, 0x10, 0x6a, 0x7e, 0x0c, 0xcd, 0x5a, 0xf3, 0x4e, 0x5a, 0x65,
	0xe9, 0x9f, 0xf0, 0x28, 0xfc, 0x35, 0x96, 0x51, 0x49, 0xf8, 0xf4, 0xf1, 0xf9, 0x12, 0x40, 0xf2,
	0x4f, 0xd4, 0x4d, 0x63, 0xd6, 0x3f, 0x7b, 0x67, 0xcf, 0xa7, 0xaf, 0x8c, 0x5f, 0x40, 0xf8, 0x93,
	0x17, 0x5f, 0xaa, 0x45, 0x65, 0x72, 0x95, 0x64, 0xd0, 0xae, 0xa9, 0x41, 0x5d, 0xc8, 0xbb, 0x37,
	0x65, 0x69, 0xdd, 0x58, 0x88, 0x95, 0x15, 0x75, 0xe7, 0xd2, 0x14, 0x27, 0xab, 0xbd, 0x72, 0x9a,
	0x8f, 0x1a, 0x59, 0x3a, 0xec, 0xb3, 0x60, 0x14, 0x4a, 0x6b, 0x0b, 0x93, 0xfb, 0xcf, 0xc5, 0xad,
	0x23, 0x1c, 0xaf, 0x39, 0xd3, 0x18, 0x1a, 0x47, 0xc3, 0x21, 0xdf, 0x81, 0x8e, 0xc1, 0x4a, 0x16,
	0x66, 0x16, 0x5b, 0xf9, 0x58, 0x90, 0x9c, 0xf1, 0x16, 0x34, 0xdf, 0x02, 0xf6, 0xff, 0x2a, 0xa8,
	0xb2, 0xeb, 0x96, 0x9f, 0xed, 0xf0, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x04, 0xcb, 0x37, 0x46, 0x98,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingPongClient is the client API for PingPong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingPongClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/v1.PingPong/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingPongServer is the server API for PingPong service.
type PingPongServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedPingPongServer can be embedded to have forward compatible implementations.
type UnimplementedPingPongServer struct {
}

func (*UnimplementedPingPongServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PingPong/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingPong_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingpong.proto",
}
